# Raw Dataset Processor

Pipeline monitoring untuk mengubah raw dataset `datasets/url_discovery/*.json` menjadi kandidat dataset dengan schema seperti `datasets/v1_shs_datasets.csv`. Notebook ini tidak menyimpan output secara otomatis.

## 1. Setup

In [1]:
from pathlib import Path
import sys

import polars as pl
from IPython.display import display


def find_project_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / "config.py").exists() and (candidate / "services").is_dir():
            return candidate
    raise FileNotFoundError("Root proyek tidak ditemukan")


PROJECT_ROOT = find_project_root(Path.cwd())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import config
from services.dataset_service import DatasetService

pl.Config.set_tbl_hide_column_data_types(True)
pl.Config.set_tbl_cell_alignment("LEFT")
pl.Config.set_fmt_str_lengths(250)
pl.Config.set_tbl_width_chars(180)
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(20)

dataset_service = DatasetService()
RAW_FOLDER = config.DATASETS / "url_discovery"
RESEARCH_CONFIG_PATH = PROJECT_ROOT / "research_config.json"
REFERENCE_DATASET_PATH = config.DATASETS / "reference_datasets.csv"

print(f"Raw folder: {RAW_FOLDER}")
print(f"Research config: {RESEARCH_CONFIG_PATH}")
print(f"Reference schema: {REFERENCE_DATASET_PATH}")

Raw folder: E:\School\tugas-akhir\project\datasets\url_discovery
Research config: E:\School\tugas-akhir\project\research_config.json
Reference schema: E:\School\tugas-akhir\project\datasets\reference_datasets.csv

## 2. Load Config dan Raw Discovery

In [2]:
research_config = dataset_service.load_research_config(RESEARCH_CONFIG_PATH)
meta_df = dataset_service.load_url_discovery_meta(RAW_FOLDER)
queries_df = dataset_service.load_url_discovery_queries(RAW_FOLDER)
raw_records_df = dataset_service.load_url_discovery_records(RAW_FOLDER)

RECORDS_FILTER_CONDITIONS = [
    # pl.col("content_status") == "success",
    # pl.col("content_text").fill_null("").str.strip_chars().str.len_chars() > 0,
    # ~pl.col("domain").str.contains("instagram.com|tiktok.com|facebook.com"),
]


def apply_filter_conditions(df: pl.DataFrame, conditions: list) -> pl.DataFrame:
    if not conditions:
        return df
    expression = conditions[0]
    for condition in conditions[1:]:
        expression = expression & condition
    return df.filter(expression)


records_df = apply_filter_conditions(raw_records_df, RECORDS_FILTER_CONDITIONS)

print("Search label:", research_config.get("search_label"))
print("Primary location:", research_config.get("primary_location"))
print(f"File metadata: {meta_df.height:,}")
print(f"Query rows: {queries_df.height:,}")
print(f"Raw records unik: {raw_records_df.height:,}")
print(f"Records setelah filter manual: {records_df.height:,}")

display(meta_df)

Search label: SHS/PLTS Kalimantan Barat
Primary location: Kalimantan Barat
File metadata: 8
Query rows: 2,067
Raw records unik: 1,364
Records setelah filter manual: 1,364

shape: (8, 7)
┌───────────────────────────────┬──────────────────────────────────┬───────────────────────────┬──────────────────────────────────────┬──────────────┬───────────────┬─────────────┐
│ source_file                   ┆ built_at                         ┆ search_label              ┆ source_files                         ┆ record_count ┆ content_count ┆ query_count │
╞═══════════════════════════════╪══════════════════════════════════╪═══════════════════════════╪══════════════════════════════════════╪══════════════╪═══════════════╪═════════════╡
│ dataset_20260627T094855Z.json ┆ 2026-06-27T09:48:55.240893+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 214          ┆ 214           ┆ 335         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260627T101253Z.json ┆ 2026-06-27T10:12:53.267116+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 203          ┆ 203           ┆ 268         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260627T135259Z.json ┆ 2026-06-27T13:52:59.725144+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 88           ┆ 88            ┆ 197         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260628T033631Z.json ┆ 2026-06-28T03:36:31.219965+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 202          ┆ 202           ┆ 381         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260628T104512Z.json ┆ 2026-06-28T10:45:12.810124+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 136          ┆ 136           ┆ 369         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260628T113525Z.json ┆ 2026-06-28T11:35:25.172805+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 12           ┆ 12            ┆ 28          │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260628T173013Z.json ┆ 2026-06-28T17:30:13.810625+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 250          ┆ 250           ┆ 267         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
│ dataset_20260630T005918Z.json ┆ 2026-06-30T00:59:18.792990+00:00 ┆ SHS/PLTS Kalimantan Barat ┆ {"E:\Work\personal\url-discovery\dat ┆ 259          ┆ 259           ┆ 490         │
│                               ┆                                  ┆                           ┆ a\urls.json","E:\Work\personal\url-d ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ iscovery\data\contents.json","E:\Wor ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ k\personal\url-discovery\data\search ┆              ┆               ┆             │
│                               ┆                                  ┆                           ┆ _state.json"}                        ┆              ┆               ┆             │
└───────────────────────────────┴──────────────────────────────────┴───────────────────────────┴──────────────────────────────────────┴──────────────┴───────────────┴─────────────┘

## 3. Monitoring Kualitas Raw Dataset

In [3]:
status_distribution = (
    records_df.with_columns(pl.col("content_status").fill_null("missing"))
    .group_by("content_status")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
)

domain_distribution = (
    records_df.with_columns(pl.col("domain").fill_null("unknown"))
    .group_by("domain")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
    .head(20)
)

query_group_distribution = (
    records_df.with_columns(pl.col("query_group").fill_null("unknown"))
    .group_by("query_group")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
    .head(20)
)

text_length_summary = records_df.select(
    pl.len().alias("total_records"),
    (
        pl.col("content_text")
        .fill_null("")
        .str.strip_chars()
        .str.len_chars()
        > 0
    ).sum().alias("records_with_text"),
    pl.col("content_text_length").min().alias("min_text_length"),
    pl.col("content_text_length").mean().round(2).alias("avg_text_length"),
    pl.col("content_text_length").max().alias("max_text_length"),
)

display(status_distribution)
display(domain_distribution)
display(query_group_distribution)
display(text_length_summary)

shape: (5, 2)
┌────────────────┬────────┐
│ content_status ┆ jumlah │
╞════════════════╪════════╡
│ success        ┆ 1067   │
│ too_short      ┆ 200    │
│ pdf_skipped    ┆ 47     │
│ failed         ┆ 41     │
│ pending        ┆ 9      │
└────────────────┴────────┘

shape: (20, 2)
┌────────────────────────────┬────────┐
│ domain                     ┆ jumlah │
╞════════════════════════════╪════════╡
│ www.instagram.com          ┆ 530    │
│ www.tiktok.com             ┆ 190    │
│ www.facebook.com           ┆ 56     │
│ pontianakpost.jawapos.com  ┆ 32     │
│ rri.co.id                  ┆ 28     │
│ kalbar.antaranews.com      ┆ 25     │
│ www.researchgate.net       ┆ 12     │
│ id.scribd.com              ┆ 11     │
│ krisnamandiri.com          ┆ 10     │
│ www.krisnamandiriutama.com ┆ 9      │
│ www.youtube.com            ┆ 8      │
│ hijau.bisnis.com           ┆ 8      │
│ gatrik.esdm.go.id          ┆ 8      │
│ www.tempo.co               ┆ 8      │
│ pontianak.tribunnews.com   ┆ 8      │
│ regional.kompas.com        ┆ 6      │
│ solarpanelid.com           ┆ 6      │
│ ombudsman.go.id            ┆ 5      │
│ www.suara.com              ┆ 5      │
│ www.antaranews.com         ┆ 5      │
└────────────────────────────┴────────┘

shape: (20, 2)
┌─────────────────────────┬────────┐
│ query_group             ┆ jumlah │
╞═════════════════════════╪════════╡
│ core:electricity_access ┆ 232    │
│ core:grid_hybrid        ┆ 115    │
│ core:household_solar    ┆ 103    │
│ issue:benefit           ┆ 93     │
│ issue:problem           ┆ 84     │
│ social                  ┆ 75     │
│ core:technical          ┆ 68     │
│ core:government_program ┆ 67     │
│ issue:access            ┆ 62     │
│ issue:environment       ┆ 55     │
│ issue:experience        ┆ 50     │
│ entity-opinion          ┆ 48     │
│ issue:socioeconomic     ┆ 47     │
│ issue:funding           ┆ 46     │
│ site:government_program ┆ 39     │
│ pdf                     ┆ 39     │
│ issue:policy            ┆ 37     │
│ site:electricity_access ┆ 24     │
│ site:household_solar    ┆ 16     │
│ core:village_solar      ┆ 15     │
└─────────────────────────┴────────┘

shape: (1, 5)
┌───────────────┬───────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ total_records ┆ records_with_text ┆ min_text_length ┆ avg_text_length ┆ max_text_length │
╞═══════════════╪═══════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ 1364          ┆ 1099              ┆ 0               ┆ 3257.82         ┆ 33760           │
└───────────────┴───────────────────┴─────────────────┴─────────────────┴─────────────────┘

## 4. Bangun Kandidat Schema v1

In [4]:
candidate_df = dataset_service.build_v1_candidate_rows(
    records_df=records_df,
    research_config=research_config,
)

CANDIDATE_FILTER_CONDITIONS = [
    # pl.col("dataset_tier") == "C_holdout_excluded",
    # pl.col("source_type") == "social_media",
    # pl.col("source_url").str.to_lowercase().str.contains("facebook.com"),
    # ~pl.col("text").str.to_lowercase().str.contains("penayangan"),
    # pl.col("aspect").is_in(["experience", "benefit", "access"]),
]

filtered_candidate_df = apply_filter_conditions(
    candidate_df, CANDIDATE_FILTER_CONDITIONS
)

reference_df = dataset_service.load(REFERENCE_DATASET_PATH)
expected_columns = list(dataset_service.v1_dataset_columns())
missing_candidate_columns = [
    column for column in expected_columns if column not in filtered_candidate_df.columns
]
extra_candidate_columns = [
    column for column in filtered_candidate_df.columns if column not in expected_columns
]

## 5. Dataset Kandidat Siap Labeling

In [5]:
MAX_ROWS_PER_VALUE = 10

labeling_df = dataset_service.build_candidate_labeling_dataset(
    filtered_candidate_df,
    max_rows_per_value=MAX_ROWS_PER_VALUE,
)

candidate_combination_df = dataset_service.summarize_candidate_combinations(
    filtered_candidate_df
).rename({"jumlah": "jumlah_tersedia"})

valid_location_df = filtered_candidate_df.filter(
    (pl.col("is_specific_location") == True)
    & pl.col("location_source").is_in(["text", "query"])
)
valid_location_combination_df = dataset_service.summarize_candidate_combinations(
    valid_location_df
).rename({"jumlah": "jumlah_lokasi_valid"})

labeling_combination_df = dataset_service.summarize_labeling_selection_buckets(
    labeling_df
).rename({"jumlah": "jumlah_diambil"})

combination_audit_df = (
    candidate_combination_df
    .join(
        valid_location_combination_df,
        on=["combination_column", "combination_value"],
        how="left",
    )
    .join(
        labeling_combination_df,
        on=["combination_column", "combination_value"],
        how="left",
    )
    .with_columns(
        pl.col("jumlah_lokasi_valid").fill_null(0).cast(pl.Int64),
        pl.col("jumlah_diambil").fill_null(0).cast(pl.Int64),
    )
)

print(f"Candidate rows setelah filter kandidat: {filtered_candidate_df.height:,}")
print(f"Candidate rows dengan lokasi valid: {valid_location_df.height:,}")
print(f"Final siap labeling: {labeling_df.height:,}")
print(f"Maksimal data per nilai unik: {MAX_ROWS_PER_VALUE}")

display(combination_audit_df)

Candidate rows setelah filter kandidat: 1,364
Candidate rows dengan lokasi valid: 1,100
Final siap labeling: 164
Maksimal data per nilai unik: 10

shape: (18, 5)
┌────────────────────┬─────────────────────┬─────────────────┬─────────────────────┬────────────────┐
│ combination_column ┆ combination_value   ┆ jumlah_tersedia ┆ jumlah_lokasi_valid ┆ jumlah_diambil │
╞════════════════════╪═════════════════════╪═════════════════╪═════════════════════╪════════════════╡
│ source_type        ┆ academic_repository ┆ 75              ┆ 59                  ┆ 10             │
│ source_type        ┆ government_official ┆ 46              ┆ 30                  ┆ 10             │
│ source_type        ┆ online_news         ┆ 459             ┆ 362                 ┆ 10             │
│ source_type        ┆ social_media        ┆ 784             ┆ 649                 ┆ 10             │
│ aspect             ┆ access              ┆ 10              ┆ 10                  ┆ 10             │
│ aspect             ┆ benefit             ┆ 106             ┆ 82                  ┆ 10             │
│ aspect             ┆ electricity_access  ┆ 79              ┆ 71                  ┆ 10             │
│ aspect             ┆ environment         ┆ 70              ┆ 58                  ┆ 10             │
│ aspect             ┆ experience          ┆ 629             ┆ 500                 ┆ 10             │
│ aspect             ┆ general_shs         ┆ 385             ┆ 313                 ┆ 10             │
│ aspect             ┆ grid_hybrid         ┆ 49              ┆ 36                  ┆ 10             │
│ aspect             ┆ household_solar     ┆ 13              ┆ 11                  ┆ 10             │
│ aspect             ┆ problem             ┆ 18              ┆ 15                  ┆ 10             │
│ aspect             ┆ technical           ┆ 1               ┆ 1                   ┆ 1              │
│ aspect             ┆ village_solar       ┆ 4               ┆ 3                   ┆ 3              │
│ dataset_tier       ┆ A_candidate_core    ┆ 486             ┆ 384                 ┆ 10             │
│ dataset_tier       ┆ B_review_queue      ┆ 581             ┆ 475                 ┆ 10             │
│ dataset_tier       ┆ C_holdout_excluded  ┆ 297             ┆ 241                 ┆ 10             │
└────────────────────┴─────────────────────┴─────────────────┴─────────────────────┴────────────────┘

## 6. Preview Lokasi Valid

In [6]:
valid_location_columns = [
    "text_id",
    "location",
    "location_source",
    "location_match",
    "source_type",
    "aspect",
    "dataset_tier",
    "source_url",
    "query",
    "text",
]
valid_location_columns = [
    column for column in valid_location_columns if column in valid_location_df.columns
]

display(valid_location_df.select(valid_location_columns).head(10))

shape: (10, 10)
┌──────────┬─────────────┬─────────────────┬────────────────┬──────────────┬─────────────┬──────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ text_id  ┆ location    ┆ location_source ┆ location_match ┆ source_type  ┆ aspect      ┆ dataset_tier         ┆ source_url           ┆ query               ┆ text                │
╞══════════╪═════════════╪═════════════════╪════════════════╪══════════════╪═════════════╪══════════════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ RAW-0001 ┆ Singkawang  ┆ text            ┆ singkawang     ┆ online_news  ┆ experience  ┆ A_candidate_core     ┆ https://www.suarapem ┆ "elektrifikasi"     ┆ Program Listrik     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ redkalbar.com/read/n ┆ "penerangan desa"   ┆ Desa di Papua       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ asional/26062026/pro ┆ "Melawi"            ┆ Hadirkan Terang dan │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ gram-listrik-desa-di ┆ after:2024-01-01    ┆ Harapan Hingga      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ -papua-hadirkan-tera ┆ before:2026-06-27   ┆ Pelosok Negeri      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ ng-dan-harapan-hingg ┆                     ┆ Program Listrik     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ a-pelosok-negeri     ┆                     ┆ Desa di Papua       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Hadirkan Terang dan │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Harapan ... suarape │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ mredkalbar.com http │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ s://www.suarapemred │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ kalbar.com › read › │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ nasional 26062026   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ program listrik     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ desa di p…          │
│ RAW-0002 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ B_review_queue       ┆ https://www.instagra ┆ "PLTS" "hemat       ┆ Ari Yunianto on     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ m.com/reel/DaCiaOBxC ┆ tagihan listrik"    ┆ Instagram: "Bekasi  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ _d                   ┆ "Sambas"            ┆ beres. Semangat…!!  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ after:2024-01-01    ┆ Antrian project     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ installasi PLTS     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ masih full sampai   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Agustus #plts       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #panelsurya         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #offgrid #pltsatap  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #solarpanels"       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Bekasi beres.       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Semangat…!! Antrian │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ project installasi  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ PLTS ... Instagram  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ · ariyuniant0 2…    │
│ RAW-0003 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ B_review_queue       ┆ https://www.instagra ┆ "PLTS" "hemat       ┆ OIS POWER on        │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ m.com/reel/DY0bixATB ┆ tagihan listrik"    ┆ Instagram: "#PLTS   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ PD                   ┆ "Sambas"            ┆ #PanelSurya         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ after:2024-01-01    ┆ #SolarPanel         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ #EnergiTerbarukan   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #SolarEnergy" OIS   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ POWER | #PLTS       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #PanelSurya         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #SolarPanel ...     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Instagram ·         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ ois_power 6 suka ·  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ 1 bulan yang lalu 6 │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ likes, 0 comments - │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ ois_power on May    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ 26, 2026: "#PLTS    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #PanelSurya …       │
│ RAW-0004 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ B_review_queue       ┆ https://www.instagra ┆ "PLTS" "hemat       ┆ TEKNIK LISTRIK on   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ m.com/p/DRq794LgAB2  ┆ tagihan listrik"    ┆ Instagram: "Panel   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ "Sambas"            ┆ Surya Listrik       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ after:2024-01-01    ┆ (Fotovoltaik/PV)    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ adalah teknologi    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ yang mengambil      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ energi dari cahaya  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ matahari (foton),   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ bukan panas, lalu   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ mengubahnya menjadi │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ listrik DC yang     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ kemudian diubah     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ oleh Inverter       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ menjadi listrik AC  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ yang dapat …        │
│ RAW-0005 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ B_review_queue       ┆ https://www.instagra ┆ "PLTS" "hemat       ┆ Datascrip Service   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ m.com/reel/DQlfNxOAT ┆ tagihan listrik"    ┆ Center on           │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ sq                   ┆ "Sambas"            ┆ Instagram: "Waktu   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ after:2024-01-01    ┆ yg tepat untuk      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ membersihkan panel  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ surya." Waktu yg    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ tepat untuk         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ membersihkan panel  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ surya. Instagram ·  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ datascrip.service.c │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ enter.id 1 suka · 7 │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ bulan yang lalu 1   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ likes, 0 comments - │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ datascrip.service.c │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ enter.i…            │
│ RAW-0006 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ C_holdout_excluded   ┆ https://www.tiktok.c ┆ "PLTS" "hemat       ┆ TikTok - Make Your  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ om/@evanstoryyy/vide ┆ tagihan listrik"    ┆ Day Listrik Padam   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ o/764301938225108096 ┆ "Sambas"            ┆ Sumatera: Solusi    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ 7                    ┆ after:2024-01-01    ┆ PLTS dan Stok       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ Cadangan ... TikTok │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ · evanstoryy 7,2    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ rb+ penayangan      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ @evanstoryyy        │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ 7643019382251080967 │
│ RAW-0007 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ B_review_queue       ┆ https://www.instagra ┆ "tenaga surya"      ┆ Damai Cable         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ m.com/p/DP2n1gQD6J_  ┆ "listrik 24 jam"    ┆ Indonesia on        │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ "Sambas"            ┆ Instagram: "Butuh   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ after:2024-01-01    ┆ kabel panel surya?  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ Kami siap penuhi    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ kebutuhan proyek    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ energi              │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ terbarukanmu! Kuat, │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ awet, dan sudah     │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ teruji kualitasnya. │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ #damaicable" Butuh  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ kabel panel surya?  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Kami siap penuhi    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ kebutuhan ...       │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ Instagram ·         │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ damaicable…         │
│ RAW-0008 ┆ Sambas      ┆ query           ┆ sambas         ┆ social_media ┆ general_shs ┆ C_holdout_excluded   ┆ https://www.tiktok.c ┆ "tenaga surya"      ┆ TikTok - Make Your  │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ om/@bacaaja.co/video ┆ "listrik 24 jam"    ┆ Day Teknologi CSP   │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆ /7651132761448647956 ┆ "Sambas"            ┆ China di Gurun      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ after:2024-01-01    ┆ Gobi: Pembangkit    │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆ before:2026-06-27   ┆ Listrik 24 ...      │
│          ┆             ┆                 ┆                ┆              ┆             ┆                      ┆                      ┆                     ┆ TikTok · bacaaja.co │

## 7. Final Dataset Siap Labeling

In [7]:
target_columns = list(dataset_service.v1_dataset_columns())
monitoring_columns = [
    "location_source",
    "location_match",
    "is_specific_location",
    "raw_source_file",
    "raw_domain",
    "content_status",
    "query_group",
    "query",
    "raw_title",
    "raw_text_length",
]
final_labeling_columns = [
    column for column in [*target_columns, *monitoring_columns]
    if column in labeling_df.columns
]

missing_final_columns = [
    column for column in target_columns if column not in labeling_df.columns
]
extra_final_columns = [
    column for column in labeling_df.columns if column not in target_columns
]

print("Kolom target hilang:", missing_final_columns)
print("Kolom monitoring tambahan:", extra_final_columns)
print(
    "Urutan kolom target sama:",
    labeling_df.columns[: len(target_columns)] == target_columns,
)

display(labeling_df.select(final_labeling_columns))

Kolom target hilang: []
Kolom monitoring tambahan: ['raw_source_file', 'raw_domain', 'content_status', 'query_group', 'query', 'raw_title', 'raw_text_length', 'location_source', 'location_match', 'is_specific_location', 'labeling_bucket_column', 'labeling_bucket_value']
Urutan kolom target sama: True

shape: (164, 29)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┐
│ tex ┆ tex ┆ sub ┆ spe ┆ pub ┆ cor ┆ asp ┆ loc ┆ sen ┆ lab ┆ sou ┆ sou ┆ sou ┆ dat ┆ inc ┆ ver ┆ evi ┆ par ┆ dec ┆ loc ┆ loc ┆ is_ ┆ raw ┆ raw ┆ con ┆ que ┆ que ┆ raw_ti ┆ raw_t │
│ t_i ┆ t   ┆ jec ┆ ake ┆ lic ┆ pus ┆ ect ┆ ati ┆ tim ┆ el_ ┆ rce ┆ rce ┆ rce ┆ ase ┆ lus ┆ ifi ┆ den ┆ ent ┆ isi ┆ ati ┆ ati ┆ spe ┆ _so ┆ _do ┆ ten ┆ ry_ ┆ ry  ┆ tle    ┆ ext_l │
│ d   ┆     ┆ tiv ┆ r_t ┆ _op ┆ _ro ┆     ┆ on  ┆ ent ┆ sta ┆ _id ┆ _ty ┆ _ur ┆ t_t ┆ ion ┆ cat ┆ ce_ ┆ _te ┆ on_ ┆ on_ ┆ on_ ┆ cif ┆ urc ┆ mai ┆ t_s ┆ gro ┆     ┆        ┆ ength │
│     ┆     ┆ ity ┆ ype ┆ ini ┆ le  ┆     ┆     ┆ _la ┆ tus ┆     ┆ pe  ┆ l   ┆ ier ┆ _st ┆ ion ┆ sup ┆ xt_ ┆ not ┆ sou ┆ mat ┆ ic_ ┆ e_f ┆ n   ┆ tat ┆ up  ┆     ┆        ┆       │
│     ┆     ┆ _ty ┆     ┆ on_ ┆     ┆     ┆     ┆ bel ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ _st ┆ por ┆ id  ┆ e   ┆ rce ┆ ch  ┆ loc ┆ ile ┆     ┆ us  ┆     ┆     ┆        ┆       │
│     ┆     ┆ pe  ┆     ┆ sco ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ atu ┆ t_s ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆     ┆     ┆     ┆ pe  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ cor ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╡
│ RAW ┆ Ana ┆ con ┆ res ┆ con ┆ exc ┆ tec ┆ Pon ┆     ┆ unl ┆ RAW ┆ aca ┆ htt ┆ C_h ┆ hel ┆ per ┆ 0.6 ┆     ┆ con ┆ que ┆ pon ┆ tru ┆ dat ┆ jou ┆ fai ┆ pdf ┆ fil ┆ Analis ┆ 0     │
│ -07 ┆ lis ┆ tex ┆ ear ┆ tex ┆ lud ┆ hni ┆ tia ┆     ┆ abe ┆ -SR ┆ dem ┆ ps: ┆ old ┆ d_o ┆ lu_ ┆ 5   ┆     ┆ ten ┆ ry  ┆ tia ┆ e   ┆ ase ┆ rna ┆ led ┆     ┆ ety ┆ is Per ┆       │
│ 15  ┆ is  ┆ tua ┆ che ┆ tua ┆ ed  ┆ cal ┆ nak ┆     ┆ led ┆ C-0 ┆ ic_ ┆ //j ┆ out ┆ ut_ ┆ ver ┆     ┆     ┆ t_n ┆     ┆ nak ┆     ┆ t_2 ┆ l.p ┆     ┆     ┆ pe: ┆ bandin ┆       │
│     ┆ Per ┆ l_s ┆ r   ┆ l_r ┆     ┆     ┆     ┆     ┆     ┆ 715 ┆ rep ┆ our ┆ _ex ┆ not ┆ ifi ┆     ┆     ┆ ot_ ┆     ┆     ┆     ┆ 026 ┆ era ┆     ┆     ┆ pdf ┆ gan    ┆       │
│     ┆ ban ┆ our ┆     ┆ efe ┆     ┆     ┆     ┆     ┆     ┆     ┆ osi ┆ nal ┆ clu ┆ _fo ┆ kas ┆     ┆     ┆ suc ┆     ┆     ┆     ┆ 062 ┆ dab ┆     ┆     ┆ "ja ┆ Instal ┆       │
│     ┆ din ┆ ce  ┆     ┆ ren ┆     ┆     ┆     ┆     ┆     ┆     ┆ tor ┆ .pe ┆ ded ┆ r_s ┆ i   ┆     ┆     ┆ ces ┆     ┆     ┆     ┆ 8T1 ┆ an. ┆     ┆     ┆ rin ┆ asi    ┆       │
│     ┆ gan ┆     ┆     ┆ ce  ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ rad ┆     ┆ ent ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ 045 ┆ ac. ┆     ┆     ┆ gan ┆ Panel  ┆       │
│     ┆ Ins ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aba ┆     ┆ ime ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12Z ┆ id  ┆     ┆     ┆ lis ┆ Surya  ┆       │
│     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n.a ┆     ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .js ┆     ┆     ┆     ┆ tri ┆ Sistem ┆       │
│     ┆ asi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c.i ┆     ┆ cor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ k   ┆ On-Gri ┆       │
│     ┆ Pan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d/i ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PLN ┆ d ...  ┆       │
│     ┆ el  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "   ┆        ┆       │
│     ┆ Sur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ x.p ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "Po ┆        ┆       │
│     ┆ ya  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hp/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nti ┆        ┆       │
│     ┆ Sis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ jee ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ana ┆        ┆       │
│     ┆ tem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pa/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k"  ┆        ┆       │
│     ┆ On- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ art ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aft ┆        ┆       │
│     ┆ Gri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ icl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er: ┆        ┆       │
│     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e/d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆        ┆       │
│     ┆ ... ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ own ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-0 ┆        ┆       │
│     ┆ Jur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ loa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-0 ┆        ┆       │
│     ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d/2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆        ┆       │
│     ┆ Uni ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 079 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bef ┆        ┆       │
│     ┆ ver ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /12 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ore ┆        ┆       │
│     ┆ sit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :20 ┆        ┆       │
│     ┆ as  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26- ┆        ┆       │
│     ┆ Per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06- ┆        ┆       │
│     ┆ ada ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 27  ┆        ┆       │
│     ┆ ban ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ htt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ //j ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ our ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ .pe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ rad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ aba ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ n.a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ c.i ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ d › ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ art ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ icl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ e › ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ dow ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ nlo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ ad  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ 207 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ 128 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│ RAW ┆ Zon ┆ pub ┆ pub ┆ pub ┆ con ┆ vil ┆ Kay ┆     ┆ unl ┆ RAW ┆ soc ┆ htt ┆ B_r ┆ rev ┆ per ┆ 0.9 ┆     ┆ soc ┆ que ┆ suk ┆ tru ┆ dat ┆ www ┆ suc ┆ iss ┆ "en ┆ Pada 8 ┆ 1228  │
│ -02 ┆ a   ┆ lic ┆ lic ┆ lic ┆ tex ┆ lag ┆ ong ┆     ┆ abe ┆ -SR ┆ ial ┆ ps: ┆ evi ┆ iew ┆ lu_ ┆     ┆     ┆ ial ┆ ry  ┆ ada ┆ e   ┆ ase ┆ .in ┆ ces ┆ ue: ┆ erg ┆ Mei    ┆       │
│ 26  ┆ Ene ┆ _ex ┆ _us ┆ _op ┆ tua ┆ e_s ┆ Uta ┆     ┆ led ┆ C-0 ┆ _me ┆ //w ┆ ew_ ┆ _re ┆ ver ┆     ┆     ┆ _do ┆     ┆ na  ┆     ┆ t_2 ┆ sta ┆ s   ┆ ben ┆ i   ┆ 2026,  ┆       │
│     ┆ rgi ┆ pec ┆ er  ┆ ini ┆ l_e ┆ ola ┆ ra  ┆     ┆     ┆ 226 ┆ dia ┆ ww. ┆ que ┆ qui ┆ ifi ┆     ┆     ┆ mai ┆     ┆     ┆     ┆ 026 ┆ gra ┆     ┆ efi ┆ ter ┆ ZONAEB ┆       │
│     ┆ Bar ┆ tat ┆     ┆ on  ┆ vid ┆ r   ┆     ┆     ┆     ┆     ┆     ┆ ins ┆ ue  ┆ red ┆ kas ┆     ┆     ┆ n_r ┆     ┆     ┆     ┆ 062 ┆ m.c ┆     ┆ t   ┆ bar ┆ T      ┆       │
│     ┆ u   ┆ ion ┆     ┆     ┆ enc ┆     ┆     ┆     ┆     ┆     ┆     ┆ tag ┆     ┆ _be ┆ i   ┆     ┆     ┆ evi ┆     ┆     ┆     ┆ 7T1 ┆ om  ┆     ┆     ┆ uka ┆ sukses ┆       │
│     ┆ Ter ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ram ┆     ┆ for ┆     ┆     ┆     ┆ ew  ┆     ┆     ┆     ┆ 012 ┆     ┆     ┆     ┆ n"  ┆ menyel ┆       │
│     ┆ bar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .co ┆     ┆ e_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 53Z ┆     ┆     ┆     ┆ "he ┆ enggar ┆       │
│     ┆ uka ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m/r ┆     ┆ ore ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .js ┆     ┆     ┆     ┆ mat ┆ akan   ┆       │
│     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ tag ┆ ...    ┆       │
│     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /DY ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iha ┆        ┆       │
│     ┆ Ins ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bki ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆        ┆       │
│     ┆ tag ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9lv ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lis ┆        ┆       │
│     ┆ ram ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gnh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆        ┆       │
│     ┆ :   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k"  ┆        ┆       │
│     ┆ "Pa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "Su ┆        ┆       │
│     ┆ da  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kad ┆        ┆       │
│     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ana ┆        ┆       │
│     ┆ Mei ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "   ┆        ┆       │
│     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aft ┆        ┆       │
│     ┆ 6,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er: ┆        ┆       │
│     ┆ ZON ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆        ┆       │
│     ┆ AEB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-0 ┆        ┆       │
│     ┆ T   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-0 ┆        ┆       │
│     ┆ suk ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆        ┆       │
│     ┆ ses ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bef ┆        ┆       │
│     ┆ men ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ore ┆        ┆       │
│     ┆ yel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :20 ┆        ┆       │
│     ┆ eng ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26- ┆        ┆       │
│     ┆ gar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06- ┆        ┆       │
│     ┆ aka ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 27  ┆        ┆       │
│     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ gra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ SIN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ AR  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ (Si ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ ner ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ gi  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ Ene ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ rgi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ Ter ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ bar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ uka ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ uk  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ Rak ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │
│     ┆ yat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       │

In [8]:
tier_distribution = (
    filtered_candidate_df.group_by("dataset_tier")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
)

inclusion_distribution = (
    filtered_candidate_df.group_by("inclusion_status")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
)

source_type_distribution = (
    filtered_candidate_df.group_by("source_type")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
)

aspect_distribution = (
    filtered_candidate_df.group_by("aspect")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
    .head(20)
)


location_distribution = (
    filtered_candidate_df.group_by("location")
    .agg(pl.len().alias("jumlah"))
    .sort("jumlah", descending=True)
    .head(20)
)

display(tier_distribution)
display(inclusion_distribution)
display(source_type_distribution)
display(aspect_distribution)
display(location_distribution)

shape: (3, 2)
┌────────────────────┬────────┐
│ dataset_tier       ┆ jumlah │
╞════════════════════╪════════╡
│ B_review_queue     ┆ 581    │
│ A_candidate_core   ┆ 486    │
│ C_holdout_excluded ┆ 297    │
└────────────────────┴────────┘

shape: (3, 2)
┌─────────────────────────────────┬────────┐
│ inclusion_status                ┆ jumlah │
╞═════════════════════════════════╪════════╡
│ review_required_before_core     ┆ 581    │
│ candidate_analysis_ready        ┆ 486    │
│ held_out_not_for_sentiment_core ┆ 297    │
└─────────────────────────────────┴────────┘

shape: (4, 2)
┌─────────────────────┬────────┐
│ source_type         ┆ jumlah │
╞═════════════════════╪════════╡
│ social_media        ┆ 784    │
│ online_news         ┆ 459    │
│ academic_repository ┆ 75     │
│ government_official ┆ 46     │
└─────────────────────┴────────┘

shape: (11, 2)
┌────────────────────┬────────┐
│ aspect             ┆ jumlah │
╞════════════════════╪════════╡
│ experience         ┆ 629    │
│ general_shs        ┆ 385    │
│ benefit            ┆ 106    │
│ electricity_access ┆ 79     │
│ environment        ┆ 70     │
│ grid_hybrid        ┆ 49     │
│ problem            ┆ 18     │
│ household_solar    ┆ 13     │
│ access             ┆ 10     │
│ village_solar      ┆ 4      │
│ technical          ┆ 1      │
└────────────────────┴────────┘

shape: (20, 2)
┌──────────────────┬────────┐
│ location         ┆ jumlah │
╞══════════════════╪════════╡
│ Kalimantan Barat ┆ 216    │
│ Pontianak        ┆ 129    │
│ Kubu Raya        ┆ 80     │
│ Ketapang         ┆ 78     │
│ Sambas           ┆ 73     │
│ Sintang          ┆ 73     │
│ Kapuas Hulu      ┆ 71     │
│ Bengkayang       ┆ 65     │
│ Sanggau          ┆ 59     │
│ Kayong Utara     ┆ 58     │
│ Landak           ┆ 55     │
│ Singkawang       ┆ 53     │
│                  ┆ 48     │
│ Sekadau          ┆ 43     │
│ Mempawah         ┆ 40     │
│ Melawi           ┆ 30     │
│ Pulau Maya       ┆ 28     │
│ Badau            ┆ 27     │
│ Teluk Batang     ┆ 15     │
│ Seluas           ┆ 14     │
└──────────────────┴────────┘

In [9]:
print(f"Candidate rows sebelum filter kandidat: {candidate_df.height:,}")
print(f"Candidate rows setelah filter kandidat: {filtered_candidate_df.height:,}")
print("Kolom wajib hilang:", missing_candidate_columns)
print("Kolom monitoring tambahan:", extra_candidate_columns)
print(
    "Urutan kolom utama sama:",
    filtered_candidate_df.columns[: len(expected_columns)] == expected_columns,
)

display(filtered_candidate_df.select(expected_columns).head(20))

Candidate rows sebelum filter kandidat: 1,364
Candidate rows setelah filter kandidat: 1,364
Kolom wajib hilang: []
Kolom monitoring tambahan: ['raw_source_file', 'raw_domain', 'content_status', 'query_group', 'query', 'raw_title', 'raw_text_length', 'location_source', 'location_match', 'is_specific_location']
Urutan kolom utama sama: True

shape: (20, 19)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ text_id ┆ text    ┆ subject ┆ speaker ┆ public_ ┆ corpus_ ┆ aspect  ┆ locatio ┆ sentim ┆ label_ ┆ source ┆ source ┆ source ┆ datase ┆ inclus ┆ verifi ┆ eviden ┆ parent ┆ decisi │
│         ┆         ┆ ivity_t ┆ _type   ┆ opinion ┆ role    ┆         ┆ n       ┆ ent_la ┆ status ┆ _id    ┆ _type  ┆ _url   ┆ t_tier ┆ ion_st ┆ cation ┆ ce_sup ┆ _text_ ┆ on_not │
│         ┆         ┆ ype     ┆         ┆ _scope  ┆         ┆         ┆         ┆ bel    ┆        ┆        ┆        ┆        ┆        ┆ atus   ┆ _statu ┆ port_s ┆ id     ┆ e      │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ s      ┆ core   ┆        ┆        │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ RAW-000 ┆ Program ┆ public_ ┆ communi ┆ public_ ┆ core_pu ┆ experie ┆ Singkaw ┆        ┆ unlabe ┆ RAW-SR ┆ online ┆ https: ┆ A_cand ┆ candid ┆ perlu_ ┆ 1.0    ┆        ┆ candid │
│ 1       ┆ Listrik ┆ expecta ┆ ty_repr ┆ opinion ┆ blic_op ┆ nce     ┆ ang     ┆        ┆ led    ┆ C-0001 ┆ _news  ┆ //www. ┆ idate_ ┆ ate_an ┆ verifi ┆        ┆        ┆ ate_fr │
│         ┆ Desa di ┆ tion    ┆ esentat ┆         ┆ inion   ┆         ┆         ┆        ┆        ┆        ┆        ┆ suarap ┆ core   ┆ alysis ┆ kasi   ┆        ┆        ┆ om_raw │
│         ┆ Papua   ┆         ┆ ive     ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ emredk ┆        ┆ _ready ┆        ┆        ┆        ┆ _disco │
│         ┆ Hadirka ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ albar. ┆        ┆        ┆        ┆        ┆        ┆ very   │
│         ┆ n       ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ com/re ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Terang  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ ad/nas ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ dan     ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ ional/ ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Harapan ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ 260620 ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Hingga  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ 26/pro ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Pelosok ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ gram-l ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Negeri  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ istrik ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Program ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ -desa- ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Listrik ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ di-pap ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Desa di ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ ua-had ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Papua   ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ irkan- ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Hadirka ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ terang ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ n       ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ -dan-h ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Terang  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ arapan ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ dan     ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ -hingg ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Harapan ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ a-pelo ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ... sua ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ sok-ne ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ rapemre ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ geri   ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ dkalbar ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ .com    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ https:/ ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ /www.su ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ arapemr ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ edkalba ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ r.com › ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ read ›  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ nasiona ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ l 26062 ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 026     ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ program ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ listrik ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ desa di ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ p…      ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ RAW-000 ┆ Ari Yun ┆ public_ ┆ public_ ┆ public_ ┆ context ┆ general ┆ Sambas  ┆        ┆ unlabe ┆ RAW-SR ┆ social ┆ https: ┆ B_revi ┆ review ┆ perlu_ ┆ 0.9    ┆        ┆ social │
│ 2       ┆ ianto   ┆ experie ┆ user    ┆ opinion ┆ ual_evi ┆ _shs    ┆         ┆        ┆ led    ┆ C-0002 ┆ _media ┆ //www. ┆ ew_que ┆ _requi ┆ verifi ┆        ┆        ┆ _domai │
│         ┆ on Inst ┆ nce     ┆         ┆         ┆ dence   ┆         ┆         ┆        ┆        ┆        ┆        ┆ instag ┆ ue     ┆ red_be ┆ kasi   ┆        ┆        ┆ n_revi │
│         ┆ agram:  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ ram.co ┆        ┆ fore_c ┆        ┆        ┆        ┆ ew     │
│         ┆ "Bekasi ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ m/reel ┆        ┆ ore    ┆        ┆        ┆        ┆        │
│         ┆ beres.  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ /DaCia ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Semanga ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ OBxC_d ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ t…!!    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Antrian ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ project ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ install ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ asi     ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ PLTS    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ masih   ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ full    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ sampai  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Agustus ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #plts   ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #panels ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ urya    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #offgri ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ d #plts ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ atap    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #solarp ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ anels"  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Bekasi  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ beres.  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Semanga ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ t…!!    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Antrian ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ project ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ install ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ asi     ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ PLTS    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ... Ins ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ tagram  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ · ariyu ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ niant0  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 2…      ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ RAW-000 ┆ OIS     ┆ public_ ┆ public_ ┆ public_ ┆ context ┆ general ┆ Sambas  ┆        ┆ unlabe ┆ RAW-SR ┆ social ┆ https: ┆ B_revi ┆ review ┆ perlu_ ┆ 0.9    ┆        ┆ social │
│ 3       ┆ POWER   ┆ experie ┆ user    ┆ opinion ┆ ual_evi ┆ _shs    ┆         ┆        ┆ led    ┆ C-0003 ┆ _media ┆ //www. ┆ ew_que ┆ _requi ┆ verifi ┆        ┆        ┆ _domai │
│         ┆ on Inst ┆ nce     ┆         ┆         ┆ dence   ┆         ┆         ┆        ┆        ┆        ┆        ┆ instag ┆ ue     ┆ red_be ┆ kasi   ┆        ┆        ┆ n_revi │
│         ┆ agram:  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ ram.co ┆        ┆ fore_c ┆        ┆        ┆        ┆ ew     │
│         ┆ "#PLTS  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ m/reel ┆        ┆ ore    ┆        ┆        ┆        ┆        │
│         ┆ #PanelS ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ /DY0bi ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ urya    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆ xATBPD ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #SolarP ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ anel    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #Energi ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ Terbaru ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ kan #So ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ larEner ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ gy" OIS ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ POWER | ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #PLTS   ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #PanelS ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ urya    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ #SolarP ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ anel    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ... Ins ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ tagram  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ · ois_p ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ ower 6  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ suka ·  ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 1 bulan ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ yang    ┆         ┆         ┆         ┆         ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │